"""
Team registry: maps an internal team key to the URL identifiers each source uses.

Ourlads: https://www.ourlads.com/ncaa-football-depth-charts/depth-chart/{ourlads_slug}/{ourlads_id}
247Sports roster: https://247sports.com/team/{sports247_slug}/Roster/

sports247_slug is optional -- teams without one just skip the composite-score/
transfer-rank step (Ourlads depth chart data still populates normally). Only
Ohio State's 247 slug has been verified so far; others can be added the same
way once needed (visit the team's 247Sports roster page and copy the slug
out of the URL).
"""

TEAMS = {
    "illinois": {
        "display_name": "Illinois",
        "ourlads_slug": "illinois",
        "ourlads_id": "90705",
        "sports247_slug": None,
    },
    "indiana": {
        "display_name": "Indiana",
        "ourlads_slug": "indiana",
        "ourlads_id": "90728",
        "sports247_slug": None,
    },
    "iowa": {
        "display_name": "Iowa",
        "ourlads_slug": "iowa",
        "ourlads_id": "90751",
        "sports247_slug": None,
    },
    "maryland": {
        "display_name": "Maryland",
        "ourlads_slug": "maryland",
        "ourlads_id": "91027",
        "sports247_slug": None,
    },
    "michigan": {
        "display_name": "Michigan",
        "ourlads_slug": "michigan",
        "ourlads_id": "91119",
        "sports247_slug": None,
    },
    "michigan-state": {
        "display_name": "Michigan State",
        "ourlads_slug": "michigan-state",
        "ourlads_id": "91142",
        "sports247_slug": None,
    },
    "minnesota": {
        "display_name": "Minnesota",
        "ourlads_slug": "minnesota",
        "ourlads_id": "91188",
        "sports247_slug": None,
    },
    "nebraska": {
        "display_name": "Nebraska",
        "ourlads_slug": "nebraska",
        "ourlads_id": "91303",
        "sports247_slug": None,
    },
    "northwestern": {
        "display_name": "Northwestern",
        "ourlads_slug": "northwestern",
        "ourlads_id": "91464",
        "sports247_slug": None,
    },
    "ohio-state": {
        "display_name": "Ohio State",
        "ourlads_slug": "ohio-state",
        "ourlads_id": "91533",
        "sports247_slug": "ohio-state-buckeyes-football-79",
    },
    "oregon": {
        "display_name": "Oregon",
        "ourlads_slug": "oregon",
        "ourlads_id": "91625",
        "sports247_slug": None,
    },
    "penn-state": {
        "display_name": "Penn State",
        "ourlads_slug": "penn-state",
        "ourlads_id": "91671",
        "sports247_slug": None,
    },
    "purdue": {
        "display_name": "Purdue",
        "ourlads_slug": "purdue",
        "ourlads_id": "91717",
        "sports247_slug": None,
    },
    "rutgers": {
        "display_name": "Rutgers",
        "ourlads_slug": "rutgers",
        "ourlads_id": "91763",
        "sports247_slug": None,
    },
    "ucla": {
        "display_name": "UCLA",
        "ourlads_slug": "ucla",
        "ourlads_id": "92223",
        "sports247_slug": None,
    },
    "usc": {
        "display_name": "USC",
        "ourlads_slug": "usc",
        "ourlads_id": "92269",
        "sports247_slug": None,
    },
    "washington": {
        "display_name": "Washington",
        "ourlads_slug": "washington",
        "ourlads_id": "92453",
        "sports247_slug": None,
    },
    "wisconsin": {
        "display_name": "Wisconsin",
        "ourlads_slug": "wisconsin",
        "ourlads_id": "92545",
        "sports247_slug": None,
    },
    "alabama": {
        "display_name": "Alabama",
        "ourlads_slug": "alabama",
        "ourlads_id": "89923",
        "sports247_slug": None,
    },
    "arkansas": {
        "display_name": "Arkansas",
        "ourlads_slug": "arkansas",
        "ourlads_id": "89992",
        "sports247_slug": None,
    },
    "auburn": {
        "display_name": "Auburn",
        "ourlads_slug": "auburn",
        "ourlads_id": "90061",
        "sports247_slug": None,
    },
    "florida": {
        "display_name": "Florida",
        "ourlads_slug": "florida",
        "ourlads_id": "90498",
        "sports247_slug": None,
    },
    "georgia": {
        "display_name": "Georgia",
        "ourlads_slug": "georgia",
        "ourlads_id": "90590",
        "sports247_slug": None,
    },
    "kentucky": {
        "display_name": "Kentucky",
        "ourlads_slug": "kentucky",
        "ourlads_id": "90866",
        "sports247_slug": None,
    },
    "lsu": {
        "display_name": "LSU",
        "ourlads_slug": "lsu",
        "ourlads_id": "90981",
        "sports247_slug": None,
    },
    "ole-miss": {
        "display_name": "Ole Miss",
        "ourlads_slug": "ole-miss",
        "ourlads_id": "91602",
        "sports247_slug": None,
    },
    "mississippi-state": {
        "display_name": "Mississippi State",
        "ourlads_slug": "mississippi-state",
        "ourlads_id": "91211",
        "sports247_slug": None,
    },
    "missouri": {
        "display_name": "Missouri",
        "ourlads_slug": "missouri",
        "ourlads_id": "91234",
        "sports247_slug": None,
    },
    "oklahoma": {
        "display_name": "Oklahoma",
        "ourlads_slug": "oklahoma",
        "ourlads_id": "91556",
        "sports247_slug": None,
    },
    "south-carolina": {
        "display_name": "South Carolina",
        "ourlads_slug": "south-carolina",
        "ourlads_id": "91832",
        "sports247_slug": None,
    },
    "tennessee": {
        "display_name": "Tennessee",
        "ourlads_slug": "tennessee",
        "ourlads_id": "91993",
        "sports247_slug": None,
    },
    "texas": {
        "display_name": "Texas",
        "ourlads_slug": "texas",
        "ourlads_id": "92016",
        "sports247_slug": None,
    },
    "texas-am": {
        "display_name": "Texas A&M",
        "ourlads_slug": "texas-am",
        "ourlads_id": "92039",
        "sports247_slug": None,
    },
    "vanderbilt": {
        "display_name": "Vanderbilt",
        "ourlads_slug": "vanderbilt",
        "ourlads_id": "92361",
        "sports247_slug": None,
    },
    "boston-college": {
        "display_name": "Boston College",
        "ourlads_slug": "boston-college",
        "ourlads_id": "90153",
        "sports247_slug": None,
    },
    "california": {
        "display_name": "California",
        "ourlads_slug": "california",
        "ourlads_id": "90245",
        "sports247_slug": None,
    },
    "clemson": {
        "display_name": "Clemson",
        "ourlads_slug": "clemson",
        "ourlads_id": "90314",
        "sports247_slug": None,
    },
    "duke": {
        "display_name": "Duke",
        "ourlads_slug": "duke",
        "ourlads_id": "90406",
        "sports247_slug": None,
    },
    "florida-state": {
        "display_name": "Florida State",
        "ourlads_slug": "florida-state",
        "ourlads_id": "90544",
        "sports247_slug": None,
    },
    "georgia-tech": {
        "display_name": "Georgia Tech",
        "ourlads_slug": "georgia-tech",
        "ourlads_id": "90613",
        "sports247_slug": None,
    },
    "louisville": {
        "display_name": "Louisville",
        "ourlads_slug": "louisville",
        "ourlads_id": "90958",
        "sports247_slug": None,
    },
    "miami-fl": {
        "display_name": "Miami",
        "ourlads_slug": "miami",
        "ourlads_id": "91073",
        "sports247_slug": None,
    },
    "north-carolina": {
        "display_name": "North Carolina",
        "ourlads_slug": "north-carolina",
        "ourlads_id": "91395",
        "sports247_slug": None,
    },
    "nc-state": {
        "display_name": "NC State",
        "ourlads_slug": "nc-state",
        "ourlads_id": "91280",
        "sports247_slug": None,
    },
    "pittsburgh": {
        "display_name": "Pittsburgh",
        "ourlads_slug": "pittsburgh",
        "ourlads_id": "91694",
        "sports247_slug": None,
    },
    "smu": {
        "display_name": "SMU",
        "ourlads_slug": "smu",
        "ourlads_id": "91809",
        "sports247_slug": None,
    },
    "stanford": {
        "display_name": "Stanford",
        "ourlads_slug": "stanford",
        "ourlads_id": "91901",
        "sports247_slug": None,
    },
    "syracuse": {
        "display_name": "Syracuse",
        "ourlads_slug": "syracuse",
        "ourlads_id": "91924",
        "sports247_slug": None,
    },
    "virginia": {
        "display_name": "Virginia",
        "ourlads_slug": "virginia",
        "ourlads_id": "92384",
        "sports247_slug": None,
    },
    "virginia-tech": {
        "display_name": "Virginia Tech",
        "ourlads_slug": "virginia-tech",
        "ourlads_id": "92407",
        "sports247_slug": None,
    },
    "wake-forest": {
        "display_name": "Wake Forest",
        "ourlads_slug": "wake-forest",
        "ourlads_id": "92430",
        "sports247_slug": None,
    },
    "notre-dame": {
        "display_name": "Notre Dame",
        "ourlads_slug": "notre-dame",
        "ourlads_id": "91487",
        "sports247_slug": None,
    },
    "arizona": {
        "display_name": "Arizona",
        "ourlads_slug": "arizona",
        "ourlads_id": "89946",
        "sports247_slug": None,
    },
    "arizona-state": {
        "display_name": "Arizona State",
        "ourlads_slug": "arizona-state",
        "ourlads_id": "89969",
        "sports247_slug": None,
    },
    "baylor": {
        "display_name": "Baylor",
        "ourlads_slug": "baylor",
        "ourlads_id": "90107",
        "sports247_slug": None,
    },
    "byu": {
        "display_name": "BYU",
        "ourlads_slug": "brigham-young",
        "ourlads_id": "90222",
        "sports247_slug": None,
    },
    "ucf": {
        "display_name": "UCF",
        "ourlads_slug": "central-florida",
        "ourlads_id": "92200",
        "sports247_slug": None,
    },
    "cincinnati": {
        "display_name": "Cincinnati",
        "ourlads_slug": "cincinnati",
        "ourlads_id": "90291",
        "sports247_slug": None,
    },
    "colorado": {
        "display_name": "Colorado",
        "ourlads_slug": "colorado",
        "ourlads_id": "90337",
        "sports247_slug": None,
    },
    "houston": {
        "display_name": "Houston",
        "ourlads_slug": "houston",
        "ourlads_id": "90659",
        "sports247_slug": None,
    },
    "iowa-state": {
        "display_name": "Iowa State",
        "ourlads_slug": "iowa-state",
        "ourlads_id": "90774",
        "sports247_slug": None,
    },
    "kansas": {
        "display_name": "Kansas",
        "ourlads_slug": "kansas",
        "ourlads_id": "90797",
        "sports247_slug": None,
    },
    "kansas-state": {
        "display_name": "Kansas State",
        "ourlads_slug": "kansas-state",
        "ourlads_id": "90820",
        "sports247_slug": None,
    },
    "oklahoma-state": {
        "display_name": "Oklahoma State",
        "ourlads_slug": "oklahoma-state",
        "ourlads_id": "91579",
        "sports247_slug": None,
    },
    "tcu": {
        "display_name": "TCU",
        "ourlads_slug": "tcu",
        "ourlads_id": "91947",
        "sports247_slug": None,
    },
    "texas-tech": {
        "display_name": "Texas Tech",
        "ourlads_slug": "texas-tech",
        "ourlads_id": "92062",
        "sports247_slug": None,
    },
    "utah": {
        "display_name": "Utah",
        "ourlads_slug": "utah",
        "ourlads_id": "92292",
        "sports247_slug": None,
    },
    "west-virginia": {
        "display_name": "West Virginia",
        "ourlads_slug": "west-virginia",
        "ourlads_id": "92499",
        "sports247_slug": None,
    },
}
